### ISSUE TITLE
make sure server validates that a token is "unblinded" before accepting it

### ISSUE THREAD

**Issue by diracdeltas** [brave-intl/challenge-bypass-server#1]
brought up in security confab, 8/1/18

amir brought up the issue that if the server holding the blinded tokens is compromised, an attacker may be able to redeem the blinded tokens.

solution: make sure server only accepts unblinded tokens as valid

**Comment by Slava** [comment]
When the client submits a redemption request, the format of the message is `(t, MAC(data))` where MAC is computed using `t` (original token), `xT` (unblinded signed token) and the request data. If a blinded token `xT` is stolen, it is still not enough to produce `MAC(data)` for any meaningful data. What do you think @diracdeltas?

**Comment by diracdeltas** [comment]
what algorithm does it use for MAC? also what is the format of xT since i'm not familiar?

**Comment by Slava** [comment]
`xT` is a point on an EC, MAC is calculated as sha256 hmac of data, where the key is derived from `t` and `xT` hmac:

https://github.com/brave-intl/challenge-bypass-server/blob/master/crypto/voprf.go#L42-L56

**Comment by diracdeltas** [comment]
@Slava so the "proof" would be:
1. given `xH_1(t)`, it should be infeasible to recover `t`
2. without t, it should be infeasible to generate `HMAC_sha256(f(t, ...), data)` (regardless of what `data` is) where f is some function of t and other stuff.

i would buy that but @riastradh-brave should check this

what is the request binding `data` actually set to in practice?

**Comment by Slava** [comment]
@diracdeltas In practice `data` is a JSON blob that can contain metadata such that "which address the payment token is redeemed towards" or "which ad creative was seen" (to determine the reward, etc)

**Comment by evq** [comment]
I'm going to close this as the protocol ensures a blinded token is not sufficient for redemption, the token preimage (`t`) is needed - as noted by @Slava.
