### ISSUE TITLE
Make challenge-bypass changes to pre-create 30 days worth of keys

### ISSUE THREAD

**Issue by mattmcalister** [brave-intl/challenge-bypass-server#106]

**Comment by v-kat** [comment]
@husobee I was having issues with docker-compose plus the server and cross compilation of the ffi for cgo linkage. I could just go forward with my old x86 machine if this is needed soon. We'll likely want to fix the aarch64 issues eventually but maybe they can wait.

**Comment by husobee** [comment]
![issuer-rotation-buffer](https://user-images.githubusercontent.com/5150259/160620611-4a7a8670-1e31-466a-beb0-c8157c0d811c.png)

I believe that the CreateIssuer and Sign APIs will need to change to allow skus to create an issuer which has the buffer time unit capabilities.  Attached is a diagram of suggested changes.

**Comment by husobee** [comment]
This new diagram utilizes the `ads-prod` kafka topics for request signing/result processing.  The `/v2/orders/` API changes are shown as well, the request does not change, but the response will be slightly different.  Instead of getting an array of signed credentials the caller will now get an array of credentials which in each entry is signed by a different sub-issuer.
![SKUsTimeLimitedV2](https://user-images.githubusercontent.com/5150259/161054423-88eb9690-8e9a-4d39-bf45-e9c6e6478a4c.png)

**Comment by husobee** [comment]
To update this: https://github.com/brave-intl/challenge-bypass-server/issues/106#issuecomment-1080984063

We will need the ability for CB to have a `/v3/issuer` API which will allow us to create an issuer which can have time limited sub-issuers.  We need in the API the ability to provide a start date/time, a sub issuer validity duration (eg P1D) and a sub issuer buffer, or the number of sub issuers to always have present. (eg 30)

We can utilize the kafka producer/consumer capabilities from SKUs service to have signing requests done, and utilize the `associated_data` field to encode the credential valid from and valid to metadata, which will be passed to the SKU SDK from the caller.

**Comment by amirsaber** [comment]
Current schema of issuers
```
challenge_bypass=> \d+ issuers;
                                                     Table "public.issuers"
    Column     |            Type             | Collation | Nullable |      Default       | Storage  | Stats target | Description
---------------+-----------------------------+-----------+----------+--------------------+----------+--------------+-------------
 issuer_type   | text                        |           | not null |                    | extended |              |
 signing_key   | text                        |           | not null |                    | extended |              |
 max_tokens    | integer                     |           | not null |                    | plain    |              |
 id            | uuid                        |           | not null | uuid_generate_v4() | plain    |              |
 created_at    | timestamp without time zone |           | not null | now()              | plain    |              |
 expires_at    | timestamp without time zone |           |          |                    | plain    |              |
 rotated_at    | timestamp without time zone |           |          |                    | plain    |              |
 version       | integer                     |           |          | 1                  | plain    |              |
 issuer_cohort | smallint                    |           |          | 1                  | plain    |              |
Indexes:
    "issuers_pkey" PRIMARY KEY, btree (id)
```
If I understood we will add  not nullable `rotation_type` column, nullables `buffer` , `days_out`, `valid_from`. 
`rotation_type` could be `static`, `XX(better name for current ones)`, `YY(better name for new ones)`

I would suggest adding `parent_id`  and `rotated_from` as references to corresponding issuers.

Currently there are two environment variables that are being applied to all issuers of first rotating type
```
ENV EXPIRATION_WINDOW=7
ENV RENEWAL_WINDOW=30
```
We should deprecate these and introduce issuer level configs.

**Comment by v-kat** [comment]
@husobee Are you going to put up a new diagram or PR?
In the meeting you had mentioned a V3 orders and some other changes to V2.
PlantUML might be nice?

**Comment by amirsaber** [comment]
![image](https://user-images.githubusercontent.com/4715448/161834082-408aa883-0008-46e6-b07b-f223d2ade8fc.png)
This is above done with PlantUML and source is located [here](https://github.com/brave-intl/bsg-cluster/blob/1a25318b2af72b805be7604ea75e63637e8abf6e/diagrams/skus-cbp.plantuml)

**Comment by husobee** [comment]
https://github.com/brave-intl/challenge-bypass-server/pull/117 contains rotation of time aware issuer keys now.  Working on redeemer/signer next, and then it should be all set.

**Comment by evq** [comment]
After the merge of ads-prod into master the PR needed to be refactored so @husobee opened it as a refresh PR, @clD11 to re-review.
