### ISSUE TITLE
Adapt the server to have issuers with a cohort

### ISSUE THREAD

**Issue by iquerejeta** [brave-intl/challenge-bypass-server#26]
- [ ] Add cohort column with type smallint to issuers table. 
- [ ] Expose an endpoint to Ads that allows Ads to supply a cohort for the 
generated tokens in the body of the request. Challenge bypass signs using the key 
from the issuer type and cohort supplied, and returns the signed tokens, public key, 
and proof.
- [ ] Expose a redemption endpoint to Ads in which the server first tries to redeem 
with cohort 1, and if that fails, tries to redeem with cohort 0. Depending on which succeeds, return the cohort of the issuer in the response.
- [ ] Alter existing token endpoints to always use the issuer with cohort 1 for signing 
blinded tokens and redemption for backwards compatibility.

**Comment by Sneagan** [comment]
@amirsaber is this ticket deprecated?

**Comment by amirsaber** [comment]
This is done and we can close it
