### ISSUE TITLE
Avoid recompiling avro deserialiser on every message

### ISSUE THREAD

**Issue by tackley** [brave-intl/challenge-bypass-server#85]
Within the per-message loop of the consumers there is code like this:

https://github.com/brave-intl/challenge-bypass-server/blob/063cb1268c070b6805d524d948a56af90f5d7217/kafka/signed_blinded_token_issuer_handler.go#L33-L37

Looking at the code behind this line, it appears to perform some quite expensive logic to use the schemas to build a message deserialiser. Since the schemas used are constant at compile time, we should only do this once on startup.

(Feel free to close this issue if profiling indicates that the code this invokes which looks expensive actually isn't.)

**Comment by Sneagan** [comment]
This function is deserializing the request data. Unfortunately, that's not something that can be done a single time as it's request dependent. Also, I'm not seeing the token issuer with a meaningful lag. It all seems to be focused around the redemption functionality.
